### PR TITLE
Enhancements to pretty indentation

### PR DESCRIPTION
**Pull request by ghost**
This pull request allows the liquor engine to accept an indentation value of 0 and still keep the newlines.

Additionally, the `index.js` file has been removed, due to the presence of a `main` property in the packages.json file. This does not affect users that `require('liquor')`.

I really like your approach on liquor, and it has become an indispensable tool for me. It is the default engine on the (soon to be released) [corejs](http://github.com/corejs) framework...

All the best,
Ernie.-

### CODE REVIEW

**Comment by chjj** [comment]
I don't want to remove index.js. This is written in pretty vanilla javascript, I want it to work with all node versions.

I don't understand the indentation part.

> This pull request allows the liquor engine to accept an indentation value of 0 and still keep the newlines.

I don't understand what you mean by "keep the newlines."

**Comment by derdesign** [comment]
My apologies, didn't know the index.js file was indeed a requirement. You're absolutely right.

Consider the following template:

``` html
<p>Number #{99}</p>

<ul>
  <li>1</li>
  <li>2</li>
</ul>

<p>Another Paragraph</p>
```

Using the following options: `{pretty: true, indent: 0}`, here's the output:

``` html
<p>Number 99</p>
<ul>
  <li>1</li>
  <li>2</li>
</ul>
<p>Another Paragraph</p>
```

Now, if you set `indent` to 1, here's what you get:

``` html
 <p>Number 99</p>

 <ul>
   <li>1</li>
   <li>2</li>
 </ul>

 <p>Another Paragraph</p>
```

As can be noticed, the line feeds are preserved as long as an indentation value >= 1 is provided.

Here is the output after the fixes, when `indent` is zero:

``` html
<p>Number 99</p>

<ul>
  <li>1</li>
  <li>2</li>
</ul>

<p>Another Paragraph</p>
```

As you notice, an indent option of zero, will not eat the line feeds. What I think is, that the `indent` option should only affect indentation, not line feeds. Additionally as you have designed it, the `indent` option is only effective if `pretty` is set to true.

**Comment by chjj** [comment]
Ah, ok. Now I see what you're saying. There's a better way of dealing with this by just changing the indentation regex. I'll fix it today.

**Comment by derdesign** [comment]
Excellent, I was suspecting there was a simpler way, I just wanted to help a bit... Didn't want to come out as the all-suggestions dude... Anything you come up with I'm happy with it :)

**Comment by derdesign** [comment]
If you've got the chance, please let me know when you fix this (tested it now and it seems to have the same behavior as before). Thanks.

**Comment by chjj** [comment]
> If you've got the chance, please let me know when you fix this (tested it now and it seems to have the same behavior as before). Thanks.

Maybe I didn't understand your problem then, because cf4f9665c23b2719face5c9fcdece3af9ff5669b fixes the problem I was thinking of.

edit: Honestly, I only really added the indent feature on a whim. I didn't say anything about it because I wasn't sure whether I wanted to keep it. It's a pretty obscure feature. I don't know how many people would actually use it.

**Comment by derdesign** [comment]
When you set indent to n, the template source will get n levels of indentation and will maintain its line feeds, as long as n is greater than zero. If n is zero, the rendered output will strip /\n+/g from the input template.

What I mean is, an indent level of zero should not affect the template in any way. Currently, it is stripping the line feeds of the prettyfied output.

Try it out with the template source I provided above.

**Comment by derdesign** [comment]
As per,the indent feature, I agree with you. I can't find a use case for this, other than making liquor not eat the newlines...

**Comment by chjj** [comment]
Oh, you _don't_ want it to eat newlines? I thought you were complaining that it wasn't eating newlines if it was indented, which is what I fixed.

**Comment by derdesign** [comment]
Exactly, the eat newlines functionality should only be effective if pretty is off.

**Comment by chjj** [comment]
I'm lost. You always want newlines to be preserved when pretty printing?

**Comment by derdesign** [comment]
Yes, exactly.

**Comment by chjj** [comment]
Alright. I'm going to remove the line feed eating and indentation feature tonight I think. I also might switch over to lib/liquor_minimal.js. I originally wrote that to be the clientside implementation, but it seems better now that I've improved it a bit, faster, more concise.

**Comment by derdesign** [comment]
Excellent! Thanks for considering my suggestions! keep up the good work.

**Pull request closed without merging**
